fieldLayouts:
  f72e8d16-0f64-49c5-9198-1bb116cd3436:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2d7d6875-fbc5-4f90-84f8-d1b0922bbcbf
            warning: null
            width: 100
          -
            fieldUid: 726b5208-c675-493d-9ba0-7ca4a203b6ba # Summary
            instructions: 'Short paragraph to describe the article.'
            label: 'Article Summary'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 828c8145-194c-423d-8298-47c161cca502
            warning: null
            width: 100
          -
            fieldUid: cc4c2be9-8ed1-400e-8694-404f83546301 # Text
            instructions: null
            label: 'Article Copy'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f606f3de-d5d7-42e1-a485-ae80fce87914
            warning: null
            width: 100
        name: Content
        uid: 8f526582-b67f-4c29-9b9c-cba112ae29e4
handle: default
hasTitleField: true
name: Default
section: 57a47b1e-d075-4211-9be0-bae0354bc0ef # Market News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
