defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  7a6a5131-23da-4dd1-8805-7832301a2333: # Crafty Bagel
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
